apiVersion: v1
kind: Service
metadata:
  name: docker-challenge-app-service
spec:
  selector:
    app: docker-challenge-app
  ports:
  - protocol: TCP
    port: 80            targetPort: 80  
  type: LoadBalancer  
