apiVersion: v1
kind: Service
metadata:
  name: docker-challenge-app-service
spec:
  selector:
    app: docker-challenge-app
  ports:
  - protocol: TCP
    port: 80        # Exposed service port
    targetPort: 80  # Container's port to route traffic to
  type: LoadBalancer  # Expose the service externally (or use NodePort if not on cloud)
